# Generated by Django 6.0 on 2026-01-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('facultad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'indexes': [models.Index(fields=['celular'], name='mensajeria__celular_ca3a31_idx'), models.Index(fields=['carrera'], name='mensajeria__carrera_dac5b7_idx')],
            },
        ),
    ]
